class Constant {
  final double margin = 25;
}

class Wilayah {
  final List<String> namaKelurahan = [
    "Kel. Fakfak Utara",
    "Kel. Fakfak Selatan",
    "Kel. Danaweria",
    "Kel. Wagom",
    "Kel. Wagom Utara",
    "Kel. Dulanpokpok",
    "Kel. Kokas Kota"
  ];

  final List<String> namaKampung = [
    "Wrikapal",
    "Lusiperi",
    "Gewerpe",
    "Kayu Merah",
    "Katemba",
    "Nemewikarya",
    "Unipokpok",
    "Raduria",
    "Brongkendik",
    "Hambrangkendik",
    "Air Besar",
    "Kanantare",
    "Mandopma",
    "Sakartemin",
    "Pasir Putih",
    "Pirma",
    "Tanama",
    "Kapaurtutin",
    "Sekban",
    "Torea",
    "Sekru",
    "Sukuru Tuare",
    "Sipatnanam",
    "Kamandu Tetar",
    "Siboru",
    "Wartutin",
    "Werabuan",
    "Werpigan",
    "Purwasak",
    "Purwahab Tonggo",
    "Werba",
    "Werba Utara",
    "Pahgar Nkindik",
    "Kwuhkendak",
    "Wurkendik",
    "Porum",
    "Kiat",
    "Weri",
    "Saharey",
    "Tunas Gain",
    "Kiriabisa",
    "Urat",
    "Sanggram",
    "Waserat",
    "Wambar",
    "Wambar Timur",
    "Kotam",
    "Kwama",
    "Kalamanuk",
    "Wayati",
    "Wayati Timur",
    "Wayati Barat",
    "Krabelang",
    "Malakuli",
    "Maas",
    "Antalisa",
    "Tarak",
    "Tuberwasak",
    "Faur",
    "Kiaba",
    "Degen",
    "Muhri",
    "Tetar",
    "Offie",
    "Tibatibananam",
    "Mawar",
    "Adora",
    "Us",
    "Puar",
    "Patipi Pasir",
    "Bisa",
    "Patipi Pulau",
    "Sum",
    "Salakiti",
    "Sengkiti",
    "Tawar",
    "Rumbati",
    "Gar",
    "Werfra",
    "Twootkendik",
    "Tanehamur",
    "Pikpik",
    "Bahbadan",
    "Kwamkwamur",
    "Nembukteb",
    "Mamur",
    "Mbaham Mayom",
    "Kramongmongga",
    "Tentreda",
    "Wargeb",
    "Gewab",
    "Ubadari",
    "Kaburbur",
    "Pattukar",
    "Homorkokma",
    "Warpa",
    "Mananmur",
    "Kayuni",
    "Kuagas",
    "Rangkendak",
    "Andamata",
    "Arguni",
    "Taver",
    "Fior",
    "Furir",
    "Kriawaswas",
    "Kampung Baru",
    "Kimina Kra",
    "Kelurahan Kokas",
    "Kinam",
    "Mandoni",
    "Mambunibuni",
    "Masina",
    "Patimburak",
    "Pangwadar",
    "Sisir",
    "Sekar",
    "Sosar",
    "Batufiafas",
    "Ugar",
    "Darembang",
    "Goras",
    "Goras Selatan",
    "Mitimber",
    "Waremu",
    "Woos",
    "Mbahamdandara",
    "Onim Sari",
    "Onim Jaya",
    "Mekar Sari",
    "Pinang Agung",
    "Wono Rejo",
    "Bumi Muroh Indah",
    "Tesha",
    "Mbima Jaya",
    "Wamar",
    "Warisa Mulya",
    "Wasa Mulya",
    "Wonodadi Mulya",
    "Otoweri",
    "Wamosan",
    "Tomage",
    "Salawir"
  ];

  List<String> namaKelurahanKampung = [
    "Kel. Fakfak Utara",
    "Kel. Fakfak Selatan",
    "Kel. Danaweria",
    "Kel. Wagom",
    "Kel. Wagom Utara",
    "Kel. Dulanpokpok",
    "Kel. Kokas Kota",
    "Adora",
    "Air Besar",
    "Andamata",
    "Antalisa",
    "Arguni",
    "Bahbadan",
    "Batufiafas",
    "Bisa",
    "Brongkendik",
    "Bumi Muroh Indah",
    "Darembang",
    "Degen",
    "Faur",
    "Fior",
    "Furir",
    "Gar",
    "Gewab",
    "Gewerpe",
    " Goras Selatan",
    "Goras",
    "Hambrangkendik",
    "Homorkokma",
    "Kaburbur",
    "Kalamanuk",
    "Kamandu Tetar",
    "Kampung Baru",
    "Kanantare",
    "Kapaurtutin",
    "Katemba",
    "Kayu Merah",
    "Kayuni",
    "Kelurahan Kokas",
    "Kiaba",
    "Kiat",
    "Kimina Kra",
    "Kinam",
    "Kiriabisa",
    "Kotam",
    "Krabelang",
    "Kramongmongga",
    "Kriawaswas",
    "Kuagas",
    "Kwama",
    "Kwamkwamur",
    "Kwuhkendak",
    "Lusiperi",
    "Maas",
    "Malakuli",
    "Mambunibuni",
    "Mamur",
    "Mananmur",
    "Mandoni",
    "Mandopma",
    "Masina",
    "Mawar",
    "Mbaham Mayom",
    "Mbahamdandara",
    "Mbima Jaya",
    "Mekar Sari",
    "Mitimber",
    "Muhri",
    "Nembukteb",
    "Nemewikarya",
    "Offie",
    "Onim Jaya",
    "Onim Sari",
    "Otoweri",
    "Pahgar Nkindik",
    "Pangwadar",
    "Pasir Putih",
    "Patimburak",
    "Patipi Pasir",
    "Patipi Pulau",
    "Pattukar",
    "Pikpik",
    "Pinang Agung",
    "Pirma",
    "Porum",
    "Puar",
    "Purwahab",
    "Tonggo",
    "Purwasak, Raduria",
    "Rangkendak",
    "Rumbati",
    "Saharey",
    "Sakartemin",
    "Salakiti",
    "Salawir",
    "Sanggram",
    "Sekar",
    "Sekban",
    "Sekru",
    "Sengkiti",
    "Siboru",
    "Sipatnanam",
    "Sisir",
    "Sosar",
    "Sukuru Tuare",
    "Sum",
    "Tanama",
    "Tanehamur",
    "Tarak",
    "Taver",
    "Tawar",
    "Tentreda",
    "Tesha",
    "Tetar",
    "Tibatibananam",
    "Tomage",
    "Torea",
    "Tuberwasak",
    "Tunas Gain",
    "Twootkendik",
    "Ubadari",
    "Ugar",
    "Unipokpok",
    "Urat",
    "Us",
    "Wamar",
    "Wambar Timur",
    "Wambar",
    "Wamosan",
    "Waremu",
    "Wargeb",
    "Warisa Mulya",
    "Warpa",
    "Wartutin",
    "Wasa Mulya",
    "Waserat",
    "Wayati Barat",
    "Wayati Timur",
    "Wayati",
    "Werabuan",
    "Werba Utara",
    "Werba",
    "Werfra",
    "Weri",
    "Werpigan",
    "Wono Rejo",
    "Wonodadi Mulya",
    "Woos",
    "Wrikapal",
    "Wurkendik"
  ];

  final List<String> namaDistrik = [
    "Arguni",
    "Bomberay",
    "Fakfak Barat",
    "Fakfak Tengah",
    "Fakfak Timur Tengah",
    "Fakfak Timur",
    "Fakfak",
    "Furwagi",
    "Karas",
    "Kayuni",
    "Kokas",
    "Kramongmongga",
    "Mbahamdandara",
    "Pariwari",
    "Teluk Patipi",
    "Tomage",
    "Wartutin"

  ];

  final List<String> namaPuskesmas = [
    "Bomberay",
    "Degen",
    "Fakfak Tengah",
    "Fakfak",
    "Karas",
    "Kokas",
    "Kramongmongga",
    "Sekban",
    "Werba",
    "Weri"
  ];

  List<String> namaPosyandu = [];

  final List<String> pendidikan = [
    "SD",
    "SMP",
    "SMA/SMK",
    "D1/D2/D3/D4",
    "S1/S2/S3"
  ];

}